<?php
$title = 'All images';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('gimager', array('action'=>'add'));?>">Add new image</a>
</p>

<table class="table">
<tr>
    <th>Image</th>
    <th>URL</th>
    <th>&nbsp;</th>
</tr>
<?php 
	foreach ($gimagers as $gimager) :
	$_url = $gimager->urlSubmitted;
	if($gimager->url != Null)
	{
		$_url = $gimager->url;
	}
?>
<tr>
    <td><?php echo $this->escapeHtml($gimager->title);?></td>
    <td><?php echo $this->escapeHtml($_url);?></td>
    <td>
        <a href="<?php echo $this->url('gimager',
            array('action'=>'editGimager', 'id' => $gimager->id));?>">Edit</a>
        <a href="<?php echo $this->url('gimager',
            array('action'=>'delete', 'id' => $gimager->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>